"""Authentication module for MSP360 API."""
import httpx
import time
import logging
from datetime import datetime, timedelta
from typing import Dict, Any
import json
import aiohttp
import asyncio
import os
import sys

# Import settings using a more robust path manipulation
current_dir = os.path.dirname(os.path.abspath(__file__))
services_dir = os.path.dirname(current_dir)
project_dir = os.path.dirname(services_dir)
msp360_mcp_dir = os.path.join(project_dir, 'msp360-mcp')

# Add the msp360-mcp directory to the path
if msp360_mcp_dir not in sys.path:
    sys.path.insert(0, msp360_mcp_dir)

# Now we can import from core
from core.config import settings

logger = logging.getLogger("msp360_mcp.auth")

class TokenManager:
    """Manages authentication tokens for MSP360 API.
    
    Implements a singleton pattern to ensure only one instance is created
    and only one token is generated.
    """
    # Class-level attributes for singleton instance
    _instance = None
    _lock = asyncio.Lock()
    _token_requests_in_progress = 0
    
    def __new__(cls, login: str, password: str, token_lifetime: int = 3600):
        """Implement the singleton pattern.
        
        Args:
            login: API login
            password: API password
            token_lifetime: Token lifetime in seconds (default: 1 hour)
            
        Returns:
            TokenManager instance (reusing existing one if available)
        """
        if cls._instance is None:
            cls._instance = super(TokenManager, cls).__new__(cls)
            cls._instance._initialized = False
        return cls._instance
    
    def __init__(self, login: str, password: str, token_lifetime: int = 3600):
        """Initialize the token manager.
        
        Args:
            login: API login
            password: API password
            token_lifetime: Token lifetime in seconds (default: 1 hour)
        """
        # Only initialize once
        if hasattr(self, '_initialized') and self._initialized:
            # Update credentials if they've changed
            if self.login != login or self.password != password:
                logger.info("Updating credentials in TokenManager singleton")
                self.login = login
                self.password = password
                self.token_lifetime = token_lifetime
                self.current_token = None
                self.token_expiry = None
            return
        
        self.login = login
        self.password = password
        self.token_lifetime = token_lifetime
        self.current_token = None
        self.token_expiry = None
        self._initialized = True
        logger.debug("Initialized TokenManager singleton")
        
    async def generate_token(self) -> str:
        """Generate a new bearer token by authenticating with the MSP360 API.
        
        Returns:
            A newly generated token or empty string if credentials are missing
        """
        # Check if credentials are available
        if not self.login or not self.password:
            logger.warning("Cannot generate token: Missing API credentials")
            return ""
            
        # Check if credentials are empty strings
        if self.login.strip() == "" or self.password.strip() == "":
            logger.warning("Cannot generate token: Empty API credentials")
            return ""
        
        # Use a lock to prevent multiple concurrent token generations
        async with self._lock:
            # Check if another request is already generating a token
            if TokenManager._token_requests_in_progress > 0:
                logger.debug("Token generation already in progress, waiting...")
                # Wait for the first request to complete
                await asyncio.sleep(0.5)
                # If we now have a valid token, return it
                if self.current_token and self.token_expiry and datetime.now() < self.token_expiry:
                    logger.debug("Using token generated by another request")
                    return self.current_token
            
            # Increment the counter for requests in progress
            TokenManager._token_requests_in_progress += 1
            
            try:
                # Use the MSP360 API to get a token
                url = f"{settings.MSP360_API_BASE_URL}/api/Provider/Login"
                
                # Using the field names expected by the API: UserName and Password
                data = {
                    "UserName": self.login,
                    "Password": self.password
                }
                
                headers = {
                    "Content-Type": "application/json"
                }
                
                try:
                    async with httpx.AsyncClient(timeout=60) as client:
                        response = await client.post(
                            url=url,
                            json=data,  # Using json parameter instead of data for JSON content type
                            headers=headers
                        )
                        
                        # Log the request for debugging
                        logger.debug(f"Auth request: URL={url}, Headers={headers}, Payload={data}")
                        logger.debug(f"Auth response status: {response.status_code}")
                        
                        # Check if we got a successful response
                        if response.status_code == 403:
                            logger.error("Authentication failed: Access Forbidden (403). This usually means invalid credentials or insufficient permissions.")
                            raise Exception("Authentication failed: 403 Forbidden. Please check your API credentials and permissions.")
                        
                        # Raise exception for other error status codes
                        response.raise_for_status()
                        
                        # Parse the response
                        try:
                            auth_data = response.json()
                            logger.info(f"Authentication response: {json.dumps(auth_data)}")
                            
                            # Check for specific response format expected from the API
                            if 'access_token' in auth_data:
                                self.current_token = auth_data['access_token']
                                
                                # Set expiry time - use the expires_in from the response if available
                                expires_in = auth_data.get('expires_in', self.token_lifetime)
                                self.token_expiry = datetime.now() + timedelta(seconds=expires_in)
                                
                                logger.info(f"Generated new MSP360 authentication token, valid until {self.token_expiry.isoformat()}")
                                return self.current_token
                            elif 'Token' in auth_data:
                                # Try alternative field name
                                self.current_token = auth_data['Token']
                                
                                # Set expiry time - use default token lifetime
                                self.token_expiry = datetime.now() + timedelta(seconds=self.token_lifetime)
                                
                                logger.info(f"Generated new MSP360 authentication token (from 'Token' field), valid until {self.token_expiry.isoformat()}")
                                return self.current_token
                            else:
                                # Log the fields available in the response
                                available_fields = list(auth_data.keys()) if isinstance(auth_data, dict) else "Not a dictionary"
                                logger.error(f"Token not found in authentication response. Available fields: {available_fields}")
                                logger.error(f"Raw response: {response.text[:500]}")
                                
                                # As a fallback, try to extract token from text using regex if the response is a string
                                if isinstance(auth_data, dict) and len(auth_data) > 0:
                                    # Try any field that might contain a token-like value
                                    for key, value in auth_data.items():
                                        if isinstance(value, str) and len(value) > 20:  # Token-like values are usually long strings
                                            logger.info(f"Using field '{key}' as potential token: {value[:10]}...")
                                            self.current_token = value
                                            self.token_expiry = datetime.now() + timedelta(seconds=self.token_lifetime)
                                            return value
                                    
                                raise Exception(f"Token not found in authentication response: {auth_data}")
                        except json.JSONDecodeError:
                            logger.error(f"Failed to parse authentication response as JSON: {response.text[:500]}")
                            raise Exception(f"Invalid JSON response from authentication endpoint: {response.text[:200]}")
                        
                except httpx.HTTPStatusError as e:
                    logger.error(f"Failed to get authentication token: {str(e)}")
                    # Log more details about the error response if available
                    if hasattr(e, 'response') and e.response is not None:
                        try:
                            error_detail = e.response.json()
                            logger.error(f"Error response details: {error_detail}")
                        except Exception:
                            logger.error(f"Error response text: {e.response.text}")
                    raise
                except Exception as e:
                    logger.error(f"Failed to get authentication token: {str(e)}")
                    raise
            finally:
                # Decrement the counter for requests in progress
                TokenManager._token_requests_in_progress -= 1
    
    async def get_valid_token(self) -> str:
        """Get a valid token, generating a new one if needed.
        
        Returns:
            A valid authentication token or empty string if credentials are missing
        """
        # Check if credentials are available
        if not self.login or not self.password:
            logger.debug("Skipping token generation: Missing API credentials")
            return ""
            
        # Check if credentials are empty strings
        if self.login.strip() == "" or self.password.strip() == "":
            logger.debug("Skipping token generation: Empty API credentials")
            return ""
        
        # If no token exists or it's expired, generate a new one
        if self.current_token is None or self.token_expiry is None or datetime.now() >= self.token_expiry:
            return await self.generate_token()
        
        # If the token will expire soon (within 5 minutes), generate a new one proactively
        if datetime.now() + timedelta(minutes=5) >= self.token_expiry:
            logger.info("Token expiring soon, generating new token")
            return await self.generate_token()
        
        return self.current_token
    
    async def get_auth_header(self) -> Dict[str, str]:
        """Get the authorization header with a valid token.
        
        Returns:
            Authorization header dictionary or empty dict if no valid token is available
        """
        token = await self.get_valid_token()
        if token:
            return {"Authorization": f"Bearer {token}"}
        return {} 